export const REGISTRATION_CITIES = [
  "Beograd",
  "Novi Sad",
  "Niš",
  "Kragujevac",
  "Subotica",
  "Zrenjanin",
  "Pančevo",
  "Čačak",
  "Kraljevo",
  "Novi Pazar",
  "Smederevo",
  "Leskovac",
  "Valjevo",
  "Kruševac",
  "Vranje",
  "Šabac",
  "Užice",
  "Sombor",
  "Požarevac",
  "Pirot",
  "Zaječar",
  "Kikinda",
  "Sremska Mitrovica",
  "Jagodina",
  "Loznica",
  "Prokuplje",
  "Bor",
  "Vršac",
  "Ruma",
  "Bačka Palanka",
  "Inđija",
  "Aranđelovac",
  "Gornji Milanovac",
  "Vrbas",
  "Apatin",
  "Negotin",
  "Drugo",
] as const;

export type RegistrationCity = (typeof REGISTRATION_CITIES)[number];

export const CITY_PLACEHOLDER = "Nije izabrano";
